#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run the build process
echo "Running build process..."
npm run build
BUILD_STATUS=$?
if [ $BUILD_STATUS -ne 0 ]; then
    echo "Build failed, aborting commit."
    exit 1
fi

# Run tests
# echo "Running tests..."
# npm test
# TEST_STATUS=$?
# if [ $TEST_STATUS -ne 0 ]; then
#     echo "Tests failed, aborting commit."
#     exit 1
# fi

# Run prettier
echo "Running prettier..."
npm run format
LINT_STATUS=$?
if [ $LINT_STATUS -ne 0 ]; then
    echo "Linting failed, aborting commit."
    exit 1
fi

# Run linter
echo "Running linter..."
npm run lint
LINT_STATUS=$?
if [ $LINT_STATUS -ne 0 ]; then
    echo "Linting failed, aborting commit."
    exit 1
fi

echo "All checks passed. Proceeding with commit."